[project]
name = "home-work"
version = "0.1.0"
description = ""
authors = [
    {name = "Your Name",email = "you@example.com"}
]
requires-python = ">=3.14"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
lint = [
    "flake8 (>=7.3.0,<8.0.0)",
    "black (>=26.3.1,<27.0.0)",
    "isort (>=8.0.1,<9.0.0)",
    "mypy (>=1.20.2,<2.0.0)"
]
dev = [
    "pytest (>=9.0.3,<10.0.0)",
    "pytest-cov (>=7.1.0,<8.0.0)",
    "requests (>=2.34.2,<3.0.0)",
    "python-dotenv (>=1.2.2,<2.0.0)",
    "mock (>=5.2.0,<6.0.0)",
    "patch (>=1.16,<2.0)"
]
[tool.black]
    line-length = 119
    exclude = '''
  /(

    | settings.py
    | _parser.py
    | files.py
)/
 '''
[tool.isort]
    line_length = 119
    skip = ["parser.py", "settings.py", "files.py"]


